config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  devise_for :users
  resources :listings
  resources :bookings
  resources :reviews, only: [:new, :create]
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  after_create :calculate_duration
  after_create :calculate_price

  def calculate_duration
    self.duration = (check_in - check_out).to_i  
    self.save  
  end

  def calculate_price
    self.total_price = duration * listing.price
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, as: :reviewable, dependent: :destroy

  has_many_attached :photos

  PROPERTY_TYPES = %w[room house apartment]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :reviewable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, 
          :recoverable, :rememberable, :validatable

  has_many_attached :photos

  has_many :listings, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :authenticate_user!
	def index
		@bookings = current_user.bookings.all
	end

	def new
		@listing = Listing.find_by(id: params[:listing_id])
		@booking = Booking.new
	end

	def create
		@listing = Listing.find_by(id: params[:booking][:listing_id])

		if available_dates?(params[:booking][:check_in],params[:booking][:check_out],@listing)
			@booking = current_user.bookings.create(booking_params)
			@booking.listing_id = @listing.id
			if @booking.save
				redirect_to booking_path(@booking)
			else
				render :new
			end
		else
			redirect_to listing_path(@listing) 
		end
	end

	def show
		@booking = Booking.find(params[:id])
	end

	def edit
	end

	def update
	end

	private
		def booking_params
			params.require(:booking).permit(:check_in, :check_out)
		end

		def available_dates?(ci_date,co_date,listing)
			overlap_bookings = 
			listing.bookings.where(check_in: ci_date..co_date)
			.or(listing.bookings.where(check_out: ci_date..co_date))
			.or(listing.bookings.where("check_in <= ? AND check_out >= ?", ci_date, co_date))

			overlap_bookings.empty?
		end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_listing, only: [:show, :edit, :update, :destroy]
	def index
		@listings = current_user.listings.all
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.create(listing_params)

		if @listing.save
			redirect_to listing_path(@listing)
		else 
			render :new 
		end		
	end

	def show
	end

	def edit
	end

	def update
		if @listing.update(listing_params)
			redirect_to listing_path(@listing)
		else
			render :edit 
		end
	end

	def destroy
		@listing.destroy

		redirect_to listings_path
	end

	private
		def set_listing
			@listing = Listing.find(params[:id])
		end

		def listing_params
			params.require(:listing).permit(:title, :description, :rooms, :capacity, :availability, :price, :location, :property_type)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		# if params[:location].blank?
		# 	@listings = Listing.all
		# else
		# 	@listings = Listing.where(location: params[:location])
		# end

		if params[:check_in].blank? or params[:check_out].blank?
			@listings = Listing.all 
		else
			@unavailable_listings = Booking.where(check_in: params[:check_in]..params[:check_out])
			.or(Booking.where(check_out: params[:check_in]..params[:check_out])).pluck(:listing_id)
			@listings = Listing.where.not(id: @unavailable_listings)
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@listing = Listing.find_by(id: params[:listing_id])
		@review = Review.new
	end

	def create
		@listing = Listing.find_by(id: params[:review][:listing_id])
		@review = current_user.reviews.create(
			comment: params[:review][:comment],
			rating: params[:review][:rating],
			reviewable_type: @listing.class,
			reviewable_id: @listing.id)

		if @review.save
			redirect_to listing_path(@listing)
		else
			render :new 
		end
	end

	# def review_params
	# 	params.require(:review).permit(:comment, :rating, :reviewable_type, :reviewable_id)
	# end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_form.html.erb
<%= form_with model: @booking do |f| %>
	<%= f.hidden_field :listing_id, value: @listing.id%>
	<%= f.date_field :check_in%>
	<br>
	<%= f.date_field :check_out%>
	<br><br>
	<%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<h1>Your Bookings</h1>

<% if @bookings.any? %>
	<% @bookings.each do |booking| %>
		<%= link_to booking_path(booking) do %>
			<%= booking.listing.title %>
		<% end %>
		<p><%= booking.check_in %> to <%= booking.check_out %></p>
	<% end %>
<% else %>
	<p>No bookings yet </p>
<% end %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<%= @listing.title %>
<br><br>
<%= render 'booking_form' %>

app/views/bookings/show.html.erb
<h1>Booking for <%= @booking.listing.title %></h1>
<h4>Hosted by <%= @booking.listing.user.email %></h4>

<br>

<p>Check in date: <%= @booking.check_in %></p>
<p>Check out date: <%= @booking.check_out %></p>
<p>Days Booked: <%= @booking.duration %></p>
<p>Total Amount: <%= @booking.total_price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body> 
  <% if user_signed_in? %>
    <%= current_user.email %>
    <div>
    <%= link_to 'Your Listings', listings_path %><br>
    <%= link_to 'Your Bookings', bookings_path %><br>
    <%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete} %>
    </div>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path %>
  <% end %>

    <%= yield %>
  
  </body>
</html>

app/views/listings/_listing_form.html.erb
<%= form_with model: @listing do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title%>
	<br>
	<%= f.label :photos%>
	<%= f.file_field :photos, multiple: true%>
	<br>
	<%= f.label :description%>
	<%= f.text_field :description%>
	<br>
	<%= f.label :property_type%>
	<%= f.text_field :property_type%>
	<br>
	<%= f.label :location%>
	<%= f.text_field :location%>	
	<br>
	<%= f.label :price%>
	<%= f.text_field :price%>
	<br>
	<%= f.label :rooms%>
	<%= f.number_field :rooms%>
	<br>
	<%= f.label :capacity%>
	<%= f.number_field :capacity%>
	<br>
	<%= f.label :available%>
	<%= f.check_box :available%>
	<br>

	
	<% if @listing.new_record? %>
			<%= f.submit'Create' %>
	<% else %>
			<%= f.submit 'Update'%>
	<% end %>
<%end%>
<br>

app/views/listings/_listings_form.html.erb
<%= form_with model: @listing do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br><br>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<br><br>
	<%= f.label :rooms %>
	<%= f.number_field :rooms %>
	<br><br>
	<%= f.label :capacity %>
	<%= f.number_field :capacity %>
	<br><br>
	<%= f.label :available %>
	<%= f.check_box :available %>
	<br><br>
	<%= f.label :property_type %>
	<%= f.text_field :property_type %>
	<br><br>
	<%= f.label :price %>
	<%= f.number_field :price %>
	<br><br>
	<%= f.label :location %>
	<%= f.text_field :location %>
	<br><br>
	<% if @listing.new_record? %>
		<%= f.submit 'Create Listing' %>
	<% else %>
		<%=	f.submit 'Update Listing' %>
	<% end %>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render 'listings_form' %>

app/views/listings/index.html.erb
<h1>Your Listings</h1>

<% if @listings.any? %>
	<% @listings.each do |listing| %>
		<%= link_to listing_path(listing) do %>
			<%= listing.title %><br><br>
		<% end %>
	<% end %>
<% else %>
	<p>No listings yet </p>
<% end %>

<%= link_to 'Create New Listing', new_listing_path %><br>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= render 'listings_form' %>

app/views/listings/show.html.erb
<h1>Title: <%= @listing.title %></h1>
<p>Description: <%= @listing.description %></p>
<p>Number of Rooms: <%= @listing.rooms %></p>
<p>Capacity: <%= @listing.capacity %></p>
<p>Location: <%= @listing.location %></p>
<p>Price: <%= @listing.price %></p>
<p>Property Type: <%= @listing.property_type %></p>
<p>Host: <%= @listing.user.email %></p>
<p>Available: <%= @listing.available %></p>

<% if current_user.id == @listing.user.id %>
	<%= link_to 'Edit Listing', edit_listing_path(@listing) %>
	<%= link_to 'Delete Listing', listing_path(@listing), data: {turbo_method: :delete, turbo_confirm: "Double confirmed?" } %>
<% end %><br>
	<%= link_to 'Make Booking', new_booking_path(listing_id: @listing.id) %>

<h3>Reviews</h3>
<% if @listing.reviews.any?%>
	<% @listing.reviews.each do |review| %>
		<li>
			<%= review.comment %> 
			(<%= review.rating %>/5)
			by <%= review.user.email %>
		</li>
	<% end %>
<% else %>
	<p>No reviews yet </p>
<% end %>
<%= link_to 'Leave a review', new_review_path(listing_id: @listing.id) %>

app/views/pages/index.html.erb
<h1>All Listings</h1>

<%= form_tag(root_path, method: :get) do %>
	<%= text_field_tag :location, params[:location] %>
	<%= submit_tag 'Search' %>
<% end %>

<%= form_tag(root_path, method: :get) do %>
	<%= date_field_tag :check_in, params[:check_in] %>
	<%= date_field_tag :check_out, params[:check_out] %>
	<%= submit_tag 'Search' %>
<% end %>

<% if @listings.any? %>
	<% @listings.each do |listing| %>
		<%= link_to listing_path(listing) do %>
			<%= listing.title %>
		<% end %>
		<p>Hosted by: <%= listing.user.email %></p>
	<% end %>
<% else %>
	<p>No listings found </p>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<h3>for <%= @listing.title %></h3>
<%= form_with model: @review do |f| %>
	<%= f.text_area :comment, placeholder: "Write your review here" %><br>
	<p>Ratings: <%= f.number_field :rating, min: 0, max: 5%></p>
	<%= f.hidden_field :listing_id, value: @listing.id%>
	<%= f.submit 'Review' %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>User Dashboard of <%= @user.email%></h1>

<%if user_signed_in? && current_user != @user%>
	<h2>Rate this user.</h2>
	<%= link_to 'Create user review', new_review_path(user_id: @user.id)%><br>
<%else%>
	<h3>Bookings</h3>
	<%if @user.bookings.any?%>
<div class="row row-cols-auto px-2">	
	<% @user.bookings.each do |booking|%>
	<div class="col-md-2" > 
		<div class="card border-success h-100 mb-3" style="width: 13rem;">
		<h4 class="text-success"><%= booking.listing.title%></h4><br>
		Check In Date: <%= booking.check_in%><br>
		Check Out Date: <%= booking.check_out%><br>
		Duration: <%= booking.duration%> days<br>
		Total Price: RM <%= booking.total_price%>
		</div>
	</div>
	<%end%>
</div>
	<%else%>
		<p>No bookings found.</p>
	<%end%>
<%end%>

<h3>User Profile Reviews</h3>
<%if @user.reviews.any?%>
<div class="row row-cols-auto px-2">	
	<% @user.reviews.each do |review|%>
	<div class="col-md-2" > 
		<div class="card border-success h-100 mb-3" style="width: 13rem;">
			<%= review.comment%><br>
			Rating: <%= review.rating%>/5 			
			<%= review.created_at%><br>
			<%= review.user.email%>				
		</div>				
	</div>
	<%end%>
</div>
<%else%>
<p>No reviews.</p>
<%end%>